### ISSUE TITLE
Sample Java Code

### ISSUE THREAD

**Issue by shifatul-i** [armcha/PlayTabLayout#1]
for people who don't know Kotlin

**Comment by shifatul-i** [comment]
Figured it out:

        PlayTabLayout playTabLayout = findViewById(R.id.play_tab_layout);
        playTabLayout.setColors(new int[]{R.color.a, R.color.b, R.color.c, R.color.d});

        ViewPager mViewPager = findViewById(R.id.view_pager);
        mViewPager.setAdapter(new PagerAdapter(getSupportFragmentManager()));

        TouchableTabLayout tabLayout = playTabLayout.getTabLayout();

        tabLayout.setupWithViewPager(mViewPager);
        tabLayout.setSelectedTabIndicatorHeight(7);
        tabLayout.setSelectedTabIndicatorColor(Color.WHITE);
        tabLayout.setTabTextColors(ContextCompat.getColor(getApplicationContext(),
                R.color.unselected_tab_color), Color.WHITE);

**Comment by re-LIFE** [comment]
not run in my app

**Comment by ghost** [comment]
@ThunderRoid  Hi  I don't know Kotlin ,Could you give me  the Java Code demo about PlayTabLayout   Thank you very much!!!

**Comment by shifatul-i** [comment]
@TonyJason The code is already posted - https://github.com/armcha/PlayTabLayout/issues/1#issuecomment-342011706

**Comment by re-LIFE** [comment]
@ThunderRoid can you give sample project?? Thanks..
