### ISSUE TITLE
Error as redeclaration of resource file- tabLayout, tabMode

### ISSUE THREAD

**Issue by jellycone** [armcha/PlayTabLayout#4]
While i complile 'com.github.armcha:PlayTabLayout:1.2.4 , I'm hitting an error that shows already defined tabLayout, tabMode ... and tab related declaration in my merged values resource file. 
How do I tackle this issue?

Thanks!

**Comment by armcha** [comment]
@jellycone Have you added support design dependency to gradle?

**Comment by armcha** [comment]
Fixed on version 2.0.0
