### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by komlan55** [armcha/PlayTabLayout#7]
When put the depency in my gradle then sync I see this compilation error

``
Android resource compilation failed
Output:  /Users/komlan/Workspaces/AndroidStudioProjects/mosala-android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1394: error: duplicate value for resource 'attr/tabMode' with config ''.
/Users/komlan/Workspaces/AndroidStudioProjects/mosala-android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1394: error: resource previously defined here.
/Users/komlan/Workspaces/AndroidStudioProjects/mosala-android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1397: error: duplicate value for resource 'attr/tabGravity' with config ''.
/Users/komlan/Workspaces/AndroidStudioProjects/mosala-android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1397: error: resource previously defined here.

Command: /Users/komlan/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-osx.jar/85efe2fe850f169e04a12731766596c9/aapt2-3.2.0-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/komlan/Workspaces/AndroidStudioProjects/mosala-android/app/build/intermediates/res/merged/debug \
        /Users/komlan/Workspaces/AndroidStudioProjects/mosala-android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.0-4818971-osx Daemon #0

``

**Comment by maleu1** [comment]
same issue here since the upgrade to support library version 28.0.0
Any ideas? Do I really need to downgrade?

**Comment by farizdotid** [comment]
same issue with buildToolsVersion 28.0.3

**Comment by armcha** [comment]
Fixed on version 2.0.0

**Comment by maleu1** [comment]
Thanks!

**Comment by imononoke** [comment]
Add design support library.
